# Gane properties
# Screen resolution
SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720

# Asteroid properties
# ASTEROID_SPAWN_RATE is in seconds
ASTEROID_MIN_RADIUS = 20
ASTEROID_KINDS = 3
ASTEROID_SPAWN_RATE = 1.0  
ASTEROID_MAX_RADIUS = ASTEROID_MIN_RADIUS * ASTEROID_KINDS

# Player properties
PLAYER_RADIUS = 20
PLAYER_TURN_SPEED = 150
PLAYER_MOVE_SPEED = 150

# Shot properties
PLAYER_SHOOT_SPEED = 500
PLAYER_SHOT_RADIUS = 5